print("hi welcome to my chatbot")
name = input("What is your name? ")
print("Nice name ", name)
input("what is your favourite hobby? ")
print("wow that's a nice hobby")
print("enter any two numbers")
a = int(input("enter number 1"))
b = int(input("enter number 2"))
print("Sum of ", a, " and ", b, " is ", a + b)